CREATE TABLE branches (
  id SERIAL PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  company INTEGER NOT NULL REFERENCES companies(id) ON DELETE CASCADE,

  created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp,
  updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT current_timestamp
);